# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
if: |
  branch IN (master, cran) AND \
  repo = cb4ds/canvasXpress.data